//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiffReport.Translations {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiffReport.Translations.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   The sha from which to set as the base commit. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BaseShaHelpText {
            get {
                return ResourceManager.GetString("BaseShaHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The branch which the commits are contained. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BranchDiffHelpText {
            get {
                return ResourceManager.GetString("BranchDiffHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The sha from which to compare with. Default: The tip of the selected branch. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CompareShaHelpText {
            get {
                return ResourceManager.GetString("CompareShaHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geneate a diff changelog. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DiffOptionHelpText {
            get {
                return ResourceManager.GetString("DiffOptionHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A Github PAT from a user with sufficient permissions to perform the invoked action. If empty, no GitHub Actions will be preformed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GitHubPatHelpText {
            get {
                return ResourceManager.GetString("GitHubPatHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Directory to output results to. Default: Current Directory. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OutputDirectoryHelpText {
            get {
                return ResourceManager.GetString("OutputDirectoryHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output File Name. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OutputFilenameHelpText {
            get {
                return ResourceManager.GetString("OutputFilenameHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The working directory of the git repository. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WorkingDirectoryDiffHelpText {
            get {
                return ResourceManager.GetString("WorkingDirectoryDiffHelpText", resourceCulture);
            }
        }
    }
}
